import org.apache.hadoop.fs.PathIOException;
public class FunctionUse2652 {
public void funcUse() {
PathIOException pathioexception = new PathIOException();
pathioexception.withFullyQualifiedPath(null);
}
}